### ISSUE TITLE
can not connect to vclient

### ISSUE THREAD

**Issue by portboy** [michelde/openv-vcontrold-docker#1]
When I start the container, I get the following log:

```
Device /dev/vitocal
chmod: cannot access '/dev/vitocal': No such file or directory
vcontrold gestartet (PID )
MQTT: aktiv (var = true)
Aktualisierungsintervall: 60 sec
Lese Parameter: 
SRV ERR: command unknown
server error
parse error: Invalid numeric literal at line 1, column 3
SRV ERR: command unknown
server error

```

This is my compose file:
```
version: '3.1'
services:
  vcontrold:
    image: michelmu/vcontrold-openv-mqtt:latest
    container_name: vcontrold
    restart: always
    devices:
      - "/dev/lesekopf_vissmann:/dev/lesekopf_vissmann"
    environment:
      MQTTHOST: "192.168.1.10"
      MQTTPORT: "1883"
      MQTTTOPIC: "openv"
      MQTTACTIVE: "true"
      INTERVAL: "60"
      #COMMANDS: ${COMMANDS}
    volumes:
      - "/mnt/user/appdata/openv:/config"
```
