### ISSUE TITLE
deamon use wrong config files for mqtt pull

### ISSUE THREAD

**Issue by portboy** [michelde/openv-vcontrold-docker#2]
If I work with my own config files for vito.xml and vcontrold.xml, the mqtt script don’t use them.
The startupscript always use the config files from "/etc/vcontrold".
So I can log into the container an manually setup commands like "vclient -h 127.0.0.1 -p 3002 -c getxxxx".
For this case the daemon use my files from the "/config" folder.
The script for the "mqtt pull/push" don’t use the files from the config folder. It uses the files from "/etc/vcontrold".

**Comment by michelde** [comment]
Sending and receiving mqtt is done using the scripts from config folder. See `startup.sh` line 24 and 27.

**Comment by portboy** [comment]
thx for the fast rpl.
I saw these lines :)
But isn't it an issue, that the container loads the wrong vito and vcontrol into "/etc/vcontrold"?

**Comment by portboy** [comment]
sorry for bother you, but the mqtt will not work.
I`m not so good in technical, so I must use your description.

actually I use your vcontrold.xml and vito.xml.
I enabled the debugging.

This is my compose file:
```
version: '3.1'
services:
  vcontrold:
    image: michelmu/vcontrold-openv-mqtt:latest
    container_name: vcontrold
    restart: always
    devices:
      - "/dev/lesekopf_vissmann:/dev/vitocal"
    environment:
      MQTTHOST: "192.168.1.10"
      MQTTPORT: "1883"
      MQTTTOPIC: "openv"
      MQTTACTIVE: "true"
      INTERVAL: "60"
      COMMANDS: "COMMANDS=getTempA"
    volumes:
      - "/mnt/user/appdata/openv:/config"
```
     

For the mqtt request I see the folowin error in the log:
```
[18] Wed Oct  5 21:14:23 2022 : Command: COMMANDS=getTempA
[18] Wed Oct  5 21:14:23 2022 : Command: quit
[18] Wed Oct  5 21:14:23 2022 : Process 18 released lock
[18] Wed Oct  5 21:14:23 2022 : Closed connection (fd:2)
[18] Wed Oct  5 21:14:23 2022 : Child process with PID 18 terminated
[10] Wed Oct  5 21:15:23 2022 : Client connected 127.0.0.1:48968 (FD:2)
[10] Wed Oct  5 21:15:23 2022 : Child process started with pid 34
[34] Wed Oct  5 21:15:23 2022 : Command: COMMANDS=getTempA
[34] Wed Oct  5 21:15:23 2022 : Command: quit
[34] Wed Oct  5 21:15:23 2022 : Process 34 released lock
[34] Wed Oct  5 21:15:23 2022 : Closed connection (fd:2)
[34] Wed Oct  5 21:15:23 2022 : Child process with PID 34 terminated
```

If I og on into your container and send 
`vclient -h 127.0.0.1 -p 3002 -c getTempA`
I get a result.
